# Generated by Django 4.2.7 on 2024-11-03 11:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(100, message='Rating cannot exceed 100')]),
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science'), ('TECH', 'Technology'), ('BUS', 'Business'), ('SELF', 'Self Help'), ('BIO', 'Biography'), ('HIST', 'History')], default=None, max_length=4),
        ),
    ]
