# Generated by Django 4.2.7 on 2024-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_manager', '0002_alter_book_options_book_cover_book_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('RD', 'Reading'), ('CP', 'Completed')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
