# Generated by Django 4.2.7 on 2024-12-15 18:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_manager', '0005_alter_book_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
